---
# Downloading RVM (Ruby)
 - block:
    - name: Update APT package cache
      apt: update_cache=yes
      register: r1
    - name: Import RVM GPG keys
      command: chdir=/root  gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      register: r2
    - name: Get rvm stable
      shell: \curl -sSL https://get.rvm.io | bash -s stable
      register: r3
    - name: Source the file as root user
      sudo : no
      shell: source "/home/ubuntu/.rvm/scripts/rvm"
      args: 
        executable: /bin/bash
      register: r4
    - name: Installing rvm
      command: rvm install 2.4.2
      register: r5
    - name: install gems 
      command: gem install selenium-cucumber savon log4r net-ssh net-sftp rest-client
      register: r6
    - name: Install vnc server
      command: sudo apt-get install vnc4server
      register: r7
 - name: Test previous block
   fail: msg="Previous block failed"
   when: r1|failed or r2|failed or r3|failed or r4|failed or r5|failed or r6|failed or r7|failed

