---
#Installing LAMP
 - block:
    - name: Download XAMMP
      get_url:
         url: https://www.apachefriends.org/xampp-files/5.6.30/xampp-linux-x64-5.6.30-0-installer.run
         dest: /root
      register: r1
    - name: Set permissions to XAMMP
      command: chdir=/root chmod 755 xampp-linux-x64-5.6.30-0-installer.run
      register: r2
    - name: Install python-pxpect module
      apt: name=python-pexpect state=installed
      register: r3
    - name: Go to the root direcrtory
      command: chdir=/root ls
      register: r4
    - name: Install XAMPP
      expect:
        command: ./xampp-linux-x64-5.6.30-0-installer.run
        responses:
#           (?i)XAMPP Core Files: "y"
           (?i)XAMPP Developer Files: "Y"
           (?i)Is the selection above correct?: "Y"
           (?i)Installation Directory: /bin/bash -c "echo"
           (?i)Do you want to continue?: "Y"
        timeout: 600
        echo: yes
      register: r5
    - name: Start the XAMMP services
      command: sudo /opt/lampp/lampp start
      register: r6
    - name: check if XAMMP is running
      command: sudo /opt/lampp/lampp status
      ignore_errors: yes
      changed_when: false
      register: r7
    - name: Report status of XAMPP
      fail: 
        msg: |
          Service XAMPP is not running.
      when: r7 | failed
 - name: Test previous block
   fail: msg="Previous block failed"
   when: r1|failed or r2|failed or r3|failed or r4|failed or r5|failed or r6|failed or r7|failed
