---
#Configuring the apache
 - block:
    - name: Configuring the apache
      copy:
       dest: /etc/apache2/sites-available/bugzilla.conf
       content: "ServerName localhost\n\n<Directory /var/www/html/bugzilla>\nAddHandler cgi-script .cgi\nOptions +ExecCGI\nDirectoryIndex index.cgi index.html\nAllowOverride All\n</Directory>"
      register: r1
    - name: configure apache to bugzilla
      command: chdir=/var/www/html/bugzilla/ a2ensite bugzilla
      register: r2
    - name: configure cgi expires
      command: chdir=/var/www/html/bugzilla/ a2enmod cgi headers expires
      register: r3
    - name: restart apache2 service
      command: chdir=/var/www/html/bugzilla/ service apache2 restart
      register: r4
 - name: Test previous block
   fail: msg="Previous block failed"
   when: r1|failed or r2|failed or r3|failed or r4|failed

