---
#Editing local config file
 - name: Edit local config file 
   copy:
    dest: /var/www/html/bugzilla/localconfig
    content: "$db_host = 'localhost';\n$db_name = 'bugzilla';\n$db_user = 'bugs';\n$db_pass = 'password';"
 - name: runs a perl script
   command: chdir=/var/www/html/bugzilla/ ./checksetup.pl

