---
# tasks file for bugzilla
 - include: install_mysql.yml
 - include: install_packs.yml
 - include: install_bug.yml
 - include: configure_apache.yml
 - include: install_perl.yml
 - include: fileedit.yml
 - include: testserver.yml
# - include: service.yml
