---
#Configuring httpd.conf and sending sample html file
 - name: Go to the bugzilla directory
   command: chdir=/var/www/html/bugzilla ls 
 - name: Test server
   command: chdir=/var/www/html/bugzilla ./testserver.pl http://localhost/bugzilla
 - name: Install lynx package
   apt:
    name: lynx
    state: latest
 - name: Access via web browser
   command: chdir=/var/www/html/bugzilla lynx http://localhost/bugzilla
   with_items:
      - Y
